### ISSUE TITLE
Input TextField can accept standard text.

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-calculator#2]
This should make the issue more clear:

![image](https://user-images.githubusercontent.com/17727163/102101993-9b014680-3e2b-11eb-9919-734d151359ac.png)

The Calculator will process arbitrary text as `0`. Performing any kind of math with arbitrary text is impossible.
I didn't see any exceptions in the terminal when running Calculator.

![image](https://user-images.githubusercontent.com/17727163/102102252-df8ce200-3e2b-11eb-8af5-30e6562afc67.png)

I believe this is fixable, just not sure how.

**Comment by reionwong** [comment]
Done
