### ISSUE TITLE
[TODO] 内存 / Memory

### ISSUE THREAD

**Issue by zirnc** [cyberos/cyber-calculator#5]
![image](https://user-images.githubusercontent.com/42088872/108511043-4b8f3900-72fa-11eb-9a10-730244251d7f.png)

- `MC` 清除
- `MR` 重新调用
- `M+` 增加 
- `M-` 减少
- `MS` 存储

> 我自己比较有意愿做这些功能，但是可能会有点忙 ~~，咕到暑假也说不定~~，先立个 flag。有想做的大佬也可以做了

**Comment by itsvic-dev** [comment]
This seems pretty easy. I believe we can make a `Memory` C++ QObject for this.

**Comment by zirnc** [comment]
Yes, it's pretty easy. But I just don't have time.... :( sad. I wanted to write it myself.

It would be nice if I am not a middle school student

**Comment by itsvic-dev** [comment]
I can probably work on it, no worries. Currently I'm working on documentation.

**Comment by zirnc** [comment]
> I can probably work on it, no worries. Currently I'm working on documentation.

Do you have any idea? Use VuePress? ~~I am good at it hahaha~~

**Comment by itsvic-dev** [comment]
I'm going to be using Sphinx, with https://github.com/helloSystem/docs as reference.

**Comment by zirnc** [comment]
Good idea! 🦾🦾🦾
